apiVersion : apps/v1
kind: Deployment
metadata:
  name: "test-7807"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "test-7807"
  template:
    metadata:
      labels:
        app: "test-7807"
    spec:
      containers:
        - name: "test-7807"
          image: "blazorcorehostedclient20220417162248.azurecr.io/test"
          ports:
          - containerPort: 80